[package]
name = "finder-finder"
version = "0.1.0"
description = "Finder to find Finder"
edition = "2021"
default-run = "finder-finder-native"

[lib]
name = "finder_finder_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "finder-finder-native"
path = "src/main.rs"

[build-dependencies]
cc = "1"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
